version: '3.8'
name: blogg

services:

  app:
    build: .
    restart: always
    env_file:
      - ./.env.local
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=BloggApp#1
      - POSTGRES_USER=blogger
      - POSTGRES_DB=blogg
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 127.0.0.1:9000:8080
  
volumes:
  db-data: