# Generated by Django 5.0.3 on 2024-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_order_supplied_order_total_receipt_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='deleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
